import { useState } from "react";
import { SearchOutlined } from "@ant-design/icons";
import { Button, Form, Select } from "antd";
import PlaceIcon from "@mui/icons-material/Place";
import "./index.scss";

const data = {
  "Hà Nội": [
    "Ba Đình",
    "Hoàn Kiếm",
    "Tây Hồ",
    "Long Biên",
    "Cầu Giấy",
    "Đống Đa",
    "Hai Bà Trưng",
    "Hoàng Mai",
    "Thanh Xuân",
    "Sóc Sơn",
    "Đông Anh",
    "Gia Lâm",
    "Nam Từ Liêm",
    "Thanh Trì",
    "Bắc Từ Liêm",
    "Mê Linh",
    "Hà Đông",
    "Sơn Tây",
    "Ba Vì",
    "Phúc Thọ",
    "Đan Phượng",
    "Hoài Đức",
    "Quốc Oai",
    "Thạch Thất",
    "Chương Mỹ",
    "Thanh Oai",
    "Thường Tín",
    "Phú Xuyên",
    "Ứng Hòa",
    "Mỹ Đức",
  ],
  "TP Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Bình Tân",
    "Bình Thạnh",
    "Gò Vấp",
    "Phú Nhuận",
    "Tân Bình",
    "Tân Phú",
    "Thủ Đức",
    "Bình Chánh",
    "Cần Giờ",
    "Củ Chi",
    "Hóc Môn",
    "Nhà Bè",
  ],
  "Đà Nẵng": [
    "Hải Châu",
    "Cẩm Lệ",
    "Liên Chiểu",
    "Ngũ Hành Sơn",
    "Sơn Trà",
    "Thanh Khê",
    "Hòa Vang",
    "Hoàng Sa",
  ],
  "Hải Phòng": [
    "Hồng Bàng",
    "Lê Chân",
    "Ngô Quyền",
    "Kiến An",
    "Hải An",
    "Dương Kinh",
    "Đồ Sơn",
    "An Dương",
    "An Lão",
    "Bạch Long Vĩ",
    "Cát Hải",
    "Kiến Thụy",
    "Thủy Nguyên",
    "Tiên Lãng",
    "Vĩnh Bảo",
  ],
  "Cần Thơ": [
    "Ninh Kiều",
    "Ô Môn",
    "Bình Thủy",
    "Cái Răng",
    "Thốt Nốt",
    "Cờ Đỏ",
    "Phong Điền",
    "Thới Lai",
    "Vĩnh Thạnh",
  ],
  Huế: [
    "Huế",
    "Hương Thủy",
    "Hương Trà",
    "A Lưới",
    "Nam Đông",
    "Phong Điền",
    "Phú Lộc",
    "Phú Vang",
    "Quảng Điền",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Vũng Tàu",
    "Bà Rịa",
    "Châu Đức",
    "Côn Đảo",
    "Đất Đỏ",
    "Long Điền",
    "Phú Mỹ",
    "Xuyên Mộc",
  ],
  "Bắc Giang": [
    "Bắc Giang",
    "Hiệp Hòa",
    "Lạng Giang",
    "Lục Nam",
    "Lục Ngạn",
    "Sơn Động",
    "Tân Yên",
    "Việt Yên",
    "Yên Dũng",
    "Yên Thế",
  ],
  "Bắc Kạn": [
    "Bắc Kạn",
    "Ba Bể",
    "Bạch Thông",
    "Chợ Đồn",
    "Chợ Mới",
    "Na Rì",
    "Ngân Sơn",
    "Pác Nặm",
  ],
  "Bạc Liêu": [
    "Bạc Liêu",
    "Đông Hải",
    "Giá Rai",
    "Hòa Bình",
    "Hồng Dân",
    "Phước Long",
    "Vĩnh Lợi",
  ],
  "Bắc Ninh": [
    "Bắc Ninh",
    "Gia Bình",
    "Lương Tài",
    "Quế Võ",
    "Thuận Thành",
    "Tiên Du",
    "Từ Sơn",
    "Yên Phong",
  ],
  "Bến Tre": [
    "Bến Tre",
    "Ba Tri",
    "Bình Đại",
    "Châu Thành",
    "Chợ Lách",
    "Giồng Trôm",
    "Mỏ Cày Bắc",
    "Mỏ Cày Nam",
    "Thạnh Phú",
  ],
  "Bình Định": [
    "Quy Nhơn",
    "An Lão",
    "An Nhơn",
    "Hoài Ân",
    "Hoài Nhơn",
    "Phù Cát",
    "Phù Mỹ",
    "Tây Sơn",
    "Tuy Phước",
    "Vân Canh",
    "Vĩnh Thạnh",
  ],
  "Bình Dương": [
    "Thủ Dầu Một",
    "Bàu Bàng",
    "Bến Cát",
    "Dầu Tiếng",
    "Dĩ An",
    "Phú Giáo",
    "Tân Uyên",
    "Thuận An",
  ],
  "Bình Phước": [
    "Đồng Xoài",
    "Bình Long",
    "Bù Đăng",
    "Bù Đốp",
    "Bù Gia Mập",
    "Chơn Thành",
    "Đồng Phú",
    "Hớn Quản",
    "Lộc Ninh",
    "Phú Riềng",
  ],
  "Bình Thuận": [
    "Phan Thiết",
    "La Gi",
    "Bắc Bình",
    "Đức Linh",
    "Hàm Tân",
    "Hàm Thuận Bắc",
    "Hàm Thuận Nam",
    "Phú Quý",
    "Tánh Linh",
    "Tuy Phong",
  ],
  "Cà Mau": [
    "Cà Mau",
    "Cái Nước",
    "Đầm Dơi",
    "Năm Căn",
    "Ngọc Hiển",
    "Phú Tân",
    "Thới Bình",
    "Trần Văn Thời",
    "U Minh",
  ],
  "Cao Bằng": [
    "Cao Bằng",
    "Bảo Lạc",
    "Bảo Lâm",
    "Hà Quảng",
    "Hạ Lang",
    "Hòa An",
    "Nguyên Bình",
    "Phục Hòa",
    "Quảng Uyên",
    "Thạch An",
    "Thông Nông",
    "Trà Lĩnh",
    "Trùng Khánh",
  ],
  "Đắk Lắk": [
    "Buôn Ma Thuột",
    "Buôn Đôn",
    "Cư Kuin",
    "Cư M'gar",
    "Ea H'leo",
    "Ea Kar",
    "Ea Súp",
    "Krông Ana",
    "Krông Bông",
    "Krông Búk",
    "Krông Năng",
    "Krông Pắk",
    "Lắk",
    "M'Đrắk",
  ],
  "Đắk Nông": [
    "Gia Nghĩa",
    "Cư Jút",
    "Đắk Glong",
    "Đắk Mil",
    "Đắk R'Lấp",
    "Đắk Song",
    "Krông Nô",
    "Tuy Đức",
  ],
  "Điện Biên": [
    "Điện Biên Phủ",
    "Mường Lay",
    "Điện Biên",
    "Điện Biên Đông",
    "Mường Ảng",
    "Mường Chà",
    "Mường Nhé",
    "Nậm Pồ",
    "Tủa Chùa",
    "Tuần Giáo",
  ],
  "Đồng Nai": [
    "Biên Hòa",
    "Long Khánh",
    "Cẩm Mỹ",
    "Định Quán",
    "Long Thành",
    "Nhơn Trạch",
    "Tân Phú",
    "Thống Nhất",
    "Trảng Bom",
    "Vĩnh Cửu",
    "Xuân Lộc",
  ],
  "Đồng Tháp": [
    "Cao Lãnh",
    "Sa Đéc",
    "Hồng Ngự",
    "Châu Thành",
    "Hồng Ngự",
    "Lai Vung",
    "Lấp Vò",
    "Tam Nông",
    "Tân Hồng",
    "Thanh Bình",
    "Tháp Mười",
  ],
  "Gia Lai": [
    "Pleiku",
    "An Khê",
    "Ayun Pa",
    "Chư Păh",
    "Chư Prông",
    "Chư Pưh",
    "Chư Sê",
    "Đăk Đoa",
    "Đăk Pơ",
    "Đức Cơ",
    "Ia Grai",
    "Ia Pa",
    "KBang",
    "Kông Chro",
    "Krông Pa",
    "Mang Yang",
    "Phú Thiện",
  ],
  "Hà Giang": [
    "Hà Giang",
    "Bắc Mê",
    "Bắc Quang",
    "Đồng Văn",
    "Hoàng Su Phì",
    "Mèo Vạc",
    "Quản Bạ",
    "Quang Bình",
    "Vị Xuyên",
    "Xín Mần",
    "Yên Minh",
  ],
  "Hà Nam": [
    "Phủ Lý",
    "Bình Lục",
    "Duy Tiên",
    "Kim Bảng",
    "Lý Nhân",
    "Thanh Liêm",
  ],
  "Hà Tĩnh": [
    "Hà Tĩnh",
    "Hồng Lĩnh",
    "Kỳ Anh",
    "Vũng Áng",
    "Cẩm Xuyên",
    "Can Lộc",
    "Đức Thọ",
    "Hương Khê",
    "Hương Sơn",
    "Kỳ Anh",
    "Lộc Hà",
    "Nghi Xuân",
    "Thạch Hà",
    "Vũ Quang",
  ],
  "Hải Dương": [
    "Hải Dương",
    "Chí Linh",
    "Bình Giang",
    "Cẩm Giàng",
    "Gia Lộc",
    "Kim Thành",
    "Kinh Môn",
    "Nam Sách",
    "Ninh Giang",
    "Thanh Hà",
    "Thanh Miện",
    "Tứ Kỳ",
  ],
  "Hậu Giang": [
    "Vị Thanh",
    "Ngã Bảy",
    "Long Mỹ",
    "Long Mỹ",
    "Châu Thành",
    "Châu Thành A",
    "Phụng Hiệp",
    "Vị Thủy",
  ],
  "Hòa Bình": [
    "Hòa Bình",
    "Cao Phong",
    "Đà Bắc",
    "Kim Bôi",
    "Kỳ Sơn",
    "Lạc Sơn",
    "Lạc Thủy",
    "Lương Sơn",
    "Mai Châu",
    "Tân Lạc",
    "Yên Thủy",
  ],
  "Hưng Yên": [
    "Hưng Yên",
    "Ân Thi",
    "Khoái Châu",
    "Kim Động",
    "Mỹ Hào",
    "Phù Cừ",
    "Tiên Lữ",
    "Văn Giang",
    "Văn Lâm",
    "Yên Mỹ",
  ],
  "Khánh Hòa": [
    "Nha Trang",
    "Cam Ranh",
    "Cam Lâm",
    "Diên Khánh",
    "Khánh Sơn",
    "Khánh Vĩnh",
    "Ninh Hòa",
    "Trường Sa",
    "Vạn Ninh",
  ],
  "Kiên Giang": [
    "Rạch Giá",
    "Hà Tiên",
    "An Biên",
    "An Minh",
    "Châu Thành",
    "Giang Thành",
    "Giồng Riềng",
    "Gò Quao",
    "Hòn Đất",
    "Kiên Hải",
    "Kiên Lương",
    "Phú Quốc",
    "Tân Hiệp",
    "U Minh Thượng",
    "Vĩnh Thuận",
  ],
  "Kon Tum": [
    "Kon Tum",
    "Đắk Glei",
    "Đắk Hà",
    "Đắk Tô",
    "Ia H'Drai",
    "Kon Plông",
    "Kon Rẫy",
    "Ngọc Hồi",
    "Sa Thầy",
    "Tu Mơ Rông",
  ],
  "Lai Châu": [
    "Lai Châu",
    "Mường Tè",
    "Nậm Nhùn",
    "Phong Thổ",
    "Sìn Hồ",
    "Tam Đường",
    "Tân Uyên",
    "Than Uyên",
  ],
  "Lâm Đồng": [
    "Đà Lạt",
    "Bảo Lộc",
    "Bảo Lâm",
    "Cát Tiên",
    "Đạ Huoai",
    "Đạ Tẻh",
    "Đam Rông",
    "Di Linh",
    "Đơn Dương",
    "Đức Trọng",
    "Lạc Dương",
    "Lâm Hà",
  ],
  "Lạng Sơn": [
    "Lạng Sơn",
    "Bắc Sơn",
    "Bình Gia",
    "Cao Lộc",
    "Chi Lăng",
    "Đình Lập",
    "Hữu Lũng",
    "Lộc Bình",
    "Tràng Định",
    "Văn Lãng",
    "Văn Quan",
  ],
  "Lào Cai": [
    "Lào Cai",
    "Bát Xát",
    "Bảo Thắng",
    "Bảo Yên",
    "Bắc Hà",
    "Mường Khương",
    "Sa Pa",
    "Si Ma Cai",
    "Văn Bàn",
  ],
  "Long An": [
    "Tân An",
    "Bến Lức",
    "Cần Đước",
    "Cần Giuộc",
    "Châu Thành",
    "Đức Hòa",
    "Đức Huệ",
    "Mộc Hóa",
    "Tân Hưng",
    "Tân Thạnh",
    "Tân Trụ",
    "Thạnh Hóa",
    "Thủ Thừa",
    "Vĩnh Hưng",
  ],
  "Nam Định": [
    "Nam Định",
    "Giao Thủy",
    "Hải Hậu",
    "Mỹ Lộc",
    "Nam Trực",
    "Nghĩa Hưng",
    "Trực Ninh",
    "Vụ Bản",
    "Xuân Trường",
    "Ý Yên",
  ],
  "Nghệ An": [
    "Vinh",
    "Cửa Lò",
    "Hoàng Mai",
    "Thái Hòa",
    "Anh Sơn",
    "Con Cuông",
    "Diễn Châu",
    "Đô Lương",
    "Hưng Nguyên",
    "Kỳ Sơn",
    "Nam Đàn",
    "Nghi Lộc",
    "Nghĩa Đàn",
    "Quế Phong",
    "Quỳ Châu",
    "Quỳ Hợp",
    "Quỳnh Lưu",
    "Tân Kỳ",
    "Thanh Chương",
    "Tương Dương",
    "Yên Thành",
  ],
  "Ninh Bình": [
    "Ninh Bình",
    "Tam Điệp",
    "Gia Viễn",
    "Hoa Lư",
    "Kim Sơn",
    "Nho Quan",
    "Yên Khánh",
    "Yên Mô",
  ],
  "Ninh Thuận": [
    "Phan Rang - Tháp Chàm",
    "Bác Ái",
    "Ninh Hải",
    "Ninh Phước",
    "Ninh Sơn",
    "Thuận Bắc",
    "Thuận Nam",
  ],
  "Phú Thọ": [
    "Việt Trì",
    "Phú Thọ",
    "Cẩm Khê",
    "Đoan Hùng",
    "Hạ Hòa",
    "Lâm Thao",
    "Phù Ninh",
    "Tam Nông",
    "Tân Sơn",
    "Thanh Ba",
    "Thanh Sơn",
    "Thanh Thủy",
    "Yên Lập",
  ],
  "Phú Yên": [
    "Tuy Hòa",
    "Sông Cầu",
    "Đông Hòa",
    "Đồng Xuân",
    "Phú Hòa",
    "Sơn Hòa",
    "Sông Hinh",
    "Tây Hòa",
    "Tuy An",
  ],
  "Quảng Bình": [
    "Đồng Hới",
    "Ba Đồn",
    "Bố Trạch",
    "Lệ Thủy",
    "Minh Hóa",
    "Quảng Ninh",
    "Quảng Trạch",
    "Tuyên Hóa",
  ],
  "Quảng Nam": [
    "Tam Kỳ",
    "Hội An",
    "Điện Bàn",
    "Đại Lộc",
    "Đông Giang",
    "Duy Xuyên",
    "Hiệp Đức",
    "Nam Giang",
    "Nam Trà My",
    "Nông Sơn",
    "Núi Thành",
    "Phú Ninh",
    "Phước Sơn",
    "Quế Sơn",
    "Tây Giang",
    "Thăng Bình",
    "Tiên Phước",
  ],
  "Quảng Ngãi": [
    "Quảng Ngãi",
    "Ba Tơ",
    "Bình Sơn",
    "Đức Phổ",
    "Lý Sơn",
    "Minh Long",
    "Mộ Đức",
    "Nghĩa Hành",
    "Sơn Hà",
    "Sơn Tây",
    "Sơn Tịnh",
    "Tây Trà",
    "Trà Bồng",
    "Tư Nghĩa",
  ],
  "Quảng Ninh": [
    "Hạ Long",
    "Cẩm Phả",
    "Móng Cái",
    "Uông Bí",
    "Bình Liêu",
    "Ba Chẽ",
    "Cô Tô",
    "Đầm Hà",
    "Đông Triều",
    "Hải Hà",
    "Hoành Bồ",
    "Quảng Yên",
    "Tiên Yên",
    "Vân Đồn",
  ],
  "Quảng Trị": [
    "Đông Hà",
    "Quảng Trị",
    "Cam Lộ",
    "Cồn Cỏ",
    "Đăk Rông",
    "Gio Linh",
    "Hải Lăng",
    "Hướng Hóa",
    "Triệu Phong",
    "Vĩnh Linh",
  ],
  "Sóc Trăng": [
    "Sóc Trăng",
    "Châu Thành",
    "Cù Lao Dung",
    "Kế Sách",
    "Long Phú",
    "Mỹ Tú",
    "Mỹ Xuyên",
    "Ngã Năm",
    "Thạnh Trị",
    "Trần Đề",
    "Vĩnh Châu",
  ],
  "Sơn La": [
    "Sơn La",
    "Bắc Yên",
    "Mai Sơn",
    "Mộc Châu",
    "Mường La",
    "Phù Yên",
    "Quỳnh Nhai",
    "Sông Mã",
    "Sốp Cộp",
    "Thuận Châu",
    "Vân Hồ",
    "Yên Châu",
  ],
  "Tây Ninh": [
    "Tây Ninh",
    "Bến Cầu",
    "Châu Thành",
    "Dương Minh Châu",
    "Gò Dầu",
    "Hòa Thành",
    "Tân Biên",
    "Tân Châu",
    "Trảng Bàng",
  ],
  "Thái Bình": [
    "Thái Bình",
    "Đông Hưng",
    "Hưng Hà",
    "Kiến Xương",
    "Quỳnh Phụ",
    "Thái Thụy",
    "Tiền Hải",
    "Vũ Thư",
  ],
  "Thái Nguyên": [
    "Thái Nguyên",
    "Sông Công",
    "Phổ Yên",
    "Đại Từ",
    "Định Hóa",
    "Đồng Hỷ",
    "Phú Bình",
    "Phú Lương",
    "Võ Nhai",
  ],
  "Thanh Hóa": [
    "Thanh Hóa",
    "Bỉm Sơn",
    "Sầm Sơn",
    "Bá Thước",
    "Cẩm Thủy",
    "Đông Sơn",
    "Hà Trung",
    "Hậu Lộc",
    "Hoằng Hóa",
    "Lang Chánh",
    "Mường Lát",
    "Nga Sơn",
    "Ngọc Lặc",
    "Như Thanh",
    "Như Xuân",
    "Nông Cống",
    "Quan Hóa",
    "Quan Sơn",
    "Quảng Xương",
    "Thạch Thành",
    "Thiệu Hóa",
    "Thọ Xuân",
    "Thường Xuân",
    "Triệu Sơn",
    "Vĩnh Lộc",
    "Yên Định",
  ],
  "Thừa Thiên - Huế": [
    "Huế",
    "Hương Thủy",
    "Hương Trà",
    "A Lưới",
    "Nam Đông",
    "Phong Điền",
    "Phú Lộc",
    "Phú Vang",
    "Quảng Điền",
  ],
  "Tiền Giang": [
    "Mỹ Tho",
    "Cai Lậy",
    "Gò Công",
    "Cái Bè",
    "Châu Thành",
    "Chợ Gạo",
    "Gò Công Đông",
    "Gò Công Tây",
    "Tân Phú Đông",
    "Tân Phước",
  ],
  "Trà Vinh": [
    "Trà Vinh",
    "Càng Long",
    "Cầu Kè",
    "Cầu Ngang",
    "Châu Thành",
    "Duyên Hải",
    "Tiểu Cần",
    "Trà Cú",
  ],
  "Tuyên Quang": [
    "Tuyên Quang",
    "Chiêm Hóa",
    "Hàm Yên",
    "Lâm Bình",
    "Na Hang",
    "Sơn Dương",
    "Yên Sơn",
  ],
  "Vĩnh Long": [
    "Vĩnh Long",
    "Bình Minh",
    "Bình Tân",
    "Long Hồ",
    "Mang Thít",
    "Tam Bình",
    "Trà Ôn",
    "Vũng Liêm",
  ],
  "Vĩnh Phúc": [
    "Vĩnh Yên",
    "Phúc Yên",
    "Bình Xuyên",
    "Lập Thạch",
    "Sông Lô",
    "Tam Đảo",
    "Tam Dương",
    "Vĩnh Tường",
    "Yên Lạc",
  ],
  "Yên Bái": [
    "Yên Bái",
    "Nghĩa Lộ",
    "Lục Yên",
    "Mù Cang Chải",
    "Trạm Tấu",
    "Trấn Yên",
    "Văn Chấn",
    "Văn Yên",
    "Yên Bình",
  ],
};

const InputLocation = () => {
  const [selectedCity, setSelectedCity] = useState("");
  const [districts, setDistricts] = useState([]);
  const [selectedDistrict, setSelectedDistrict] = useState("");

  const handleCityChange = (event) => {
    const city = event;
    console.log(city);
    setSelectedCity(city);
    setDistricts(data[city] || []);
    setSelectedDistrict("");
  };

  const handleDistrictChange = (event) => {
    console.log(event);
    setSelectedDistrict(event);
  };

  return (
    <div className="input-location">
      <div className="input-location-form">
        <div className="input-location-welcome">
          <h1>Xin chào!</h1>
          <span>Chơi cầu lông ngay với DatSan79</span>
        </div>

        <Form className="form-location" labelCol={{ span: 24 }}>
          <div className="form-icon">
            <PlaceIcon fontSize="large" />
          </div>
          <Form.Item className="form-item" label="Thành phố">
            <Select
              style={{ width: 200 }}
              id="city"
              value={selectedCity}
              onChange={handleCityChange}
            >
              <option value="">--Chọn Thành phố--</option>
              {Object.keys(data).map((city) => (
                <option key={city} value={city}>
                  {city}
                </option>
              ))}
            </Select>
          </Form.Item>

          {/* <div className="form-group"> */}
          <div className="form-icon">
            <PlaceIcon fontSize="large" />
          </div>

          <Form.Item className="form-item" label="Quận">
            <Select
              style={{ width: 200 }}
              id="district"
              value={selectedDistrict}
              onChange={handleDistrictChange}
              disabled={!selectedCity}
            >
              <option value="">--Chọn Quận/Huyện--</option>
              {districts.map((district) => (
                <option key={district} value={district}>
                  {district}
                </option>
              ))}
            </Select>
          </Form.Item>

          <div className="form-search">
            <Button>
              <SearchOutlined />
            </Button>
          </div>
        </Form>
      </div>
    </div>
  );
};

export default InputLocation;
